
server:
  port: 7777

spring:
  security:
    user:
      name: dev
      password: dev

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sbdb?createDatabaseIfNotExist=true
    username: root
    password: boss

  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  data:
    jpa:
      repositories:
        enabled: true

logging:
  level:
    root: INFO                # Default logging level for all packages
    com.collectors: DEBUG     # Set specific package to DEBUG level
    org.springframework: WARN # Reduce Spring framework log level to WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"  # Custom logging pattern for console output
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%"
  file:
    path: target/logs         # Folder where logs will be stored
    name: app.log             # Log file name
  logback:
    rollingpolicy:
      fileNamePattern: target/logs/app-%d{yyyy-MM-dd}.log.gz  # Rolling policy for logs inside target/logs
      maxFileSize: 10MB
      maxHistory: 30
